== Jack-O'-Lantern

by W.R.Smith
(edits and critiques welcome)

A wreath of nut-bearing branches hung on the door.
Bundled stalks of corn stood on either side.
The master of ceremonies sat patiently on the bottom step; a carved pumpkin — waiting for nightfall.
These were the kind of old fashioned homespun decorations Elma took pride in, that authenticity might speak for her.

“Lord save me from myself.
Is everything done?”

She worked her broom down the front steps, right up to the sidewalk in front of her house.
With energetic bursts of swishing and sweeping she kept herself company.
“Why is a pig in the living room like a house on fire? — Because the sooner it’s put out, the better.”

She practiced her comic timing, repeating the joke several times over.
She tried another.
“What lives to devour itself? — A candle.”

She worried the walk’s edge with the broom.
“Elma, silly fool, all your jokes are old fashioned.
Children these days just won’t get them.”

Across the street, the neighbor eased his car into the garage.
He pulled shut the big overhead door with a rattling bang and turned to his front step.

Elma called, “Halloo over there! You all ready for haunts tonight?”

The man stopped and looked at her like he’d never seen such a thing as a spry eighty-year-old woman holding a straw broom.
He’d certainly never talked to her before.
He entered his house and shut the door in reply.

None of this surprised or put off Elma.
She understood him well enough.
He was a perpetually irritable man whose best contribution to Halloween night would be to turn off the house lights and brood in the darkness — pretending he was not at home.
However, this only worked in favor of her plans.

An old-timer in the neighborhood, and the last of her generation, all her friends had moved away or passed on.
Since the close of World War II, things seemed to change so fast — to think about it made her head spin and her heart heavy.
She turned back to the only stable structure left in life — her house.

On the welcome mat was painted an arching black cat perched on the hook of a crescent moon.
She swept it again.
Trusting in the magic of her decorations to draw a line between the world, grown strange outside, from the one within, warm and welcoming, she opened the door and stepped inside.

And the magic proved true.

Festoons of black and yellow crepe ribbons, twisted in strips, hung like suspension cables from the ceiling.
Grimacing Jack-O’-Lanterns shared the company of smaller similarly carved apple’s, cucumbers, and squash.
They were placed throughout the living room, on every table, upon the mantle, and nested in the corners with golden sheaves of straw.
The smell of eugenol oil and dry corn shuck greeted her.

Construction paper figures hung.
Fluttering as she passed were pumpkins, witches bent over brooms and black cats.
She touched them here and there, like a museum curate.
They whispered a promise of laughter, fun, and mystery.

The table centerpiece was a giant pumpkin with the top cut off, filled with yellow chrysanthemums and licorice scented goldenrod.
Spread around its base were bay leaves and figures of nibbling chocolate mice.
In approval, she passed a hand across her forehead, over the sum of a week’s preparation.
Word would surely get around among kindred spirits.
The candy bowl was full.
Reserves bulged in plastic bags behind the door.
They must come, or her heart would break.

She busied herself on her left, rearranging small crystalline candy skulls, and on her right, polishing a brass candlestick holder.
She had not felt this way or worked this hard on the occasion for as long as she cared to remember.
The spirit, once the idea took hold, mercilessly drove her old bones.
She went along with the work, alternating between anticipation and worry.

At dusk, she saw from the window the first fluttering ghost two houses down.
Human parents watched from the sidewalk, as the little apparition went from door to door, taking sweet tribute for the dead.

When the first knock and cry of “Trick or treat!” came at Elma’s door she was rapturous in the answering.

“What do we have here? A Witch! My you do bring a chill to my old bones.
And you? Such big, big, teeth you have Mr.
Wolf-man.
Here you go some for you, and you, and especially you — little ghost.
Happy Halloween!”

More children hurried across the yard toward her open door — and all were satisfied.
When they had gone, Elma patted her heart as she shut the door.
Such dear little ones.

As evening turned dark, the visions presenting themselves at her door became progressively taller and more gruesomely outfitted.
This age group interested her most.
Elma left the door open and displayed the bowl of candy in plain sight.

Splendid! A teenage scarecrow, with hay sticking out from the buttons and pockets of his stuffed shirt, glanced in at the door.
He escorted Dorothy.
She wore sparkling ruby shoes and carried a plush toy dog under one arm.
Marvelous! There were more of the curious standing behind.
Elma beckoned all to enter for a drink of cider and games.
Lights were dimmed, emphasizing the glowing eyes and grins of Jack-O’-Lanterns.

Another group arrived and saw a party in the making.
They filed in and helped themselves at the candy bowl.
The living-room became a mix of various zombies, a lion tamer, comic book heroes, a mustachio villain, and the occasional likeness of a politician.
Ruddy cheeks and shining faces revealed themselves as stifling masks were pushed back and worn like hats.

Elma organized a guessing game while serving up drinks and cookies.
“Guess the object I have in mind? Keep it simple now,” she said.

After some hesitation, one answered “A monkey.”

“A candle,” said a second.

“A funny old lady,” added one.

“Fair enough!” replied Elma.

“So, tell us the answer! What were you thinking of?” someone called.

“A cat,” said Elma.
She pointed to each guesser and asked in turn.
“So tell me why is my cat like the monkey?”

“Because it is full of tricks.”

“Good! Good! Now, why is my cat like a candle?” Elma asked the second.

“Because, its eyes glow like a candle in the dark.”

“Superb! And you sir why is my cat like a funny old lady?”

The boy was too embarrassed to answer straight away.
It was then his turn to ask the room, “What something am I thinking of?”

A couple of mildly entertaining rounds of this game passed — then fizzled.
Elma draped and hooked a white tablecloth in the corner of the room.
Behind it was a bright table lamp with its shade removed.
She announced another kind of guessing game.
All remaining lights were then extinguished, except the flickering Jack-O’-Lanterns.

The game was called Shadow-Buff.
She directed her guests to form groups of two’s and three’s, each devising a secret they would act out behind the screen.
The rule was: the players must perform their roles in silence while the audience guessed the meaning behind their shadow dance.

The first scenario was a murder by knife, horrifically prolonged, even after being called.
With boos and hisses, the audience demanded the next players have their chance.
The art of the medium was quickly absorbed.
Ad-lib mimes swung freely between unbridled madness to moments of baffling brilliance.
Distorted shadows shedding inhibitions, danced and menaced while the audience shouted for more.

In another scene, a brave lion tamer turned cowardly and was shortly mauled.
Following that, a one-man show illustrated the evolution of walking posture in five stages, from primate to man.
He bent his back one final time for a sweeping bow.

The Scarecrow and Dorothy borrowed a broom from Elma.
Behind the screen, the broom hoisted over a shoulder turned into a rifle.
The boy marched in place.
The shadow-girl dabbed a tear from her eye and waved goodbye with a handkerchief.
Easily guessed, the play was only a moment long.

As the night wore down, Elma breathed a sigh of relief for the success of the party.
The crowd thinned as the guests said goodnight.
Elma lingered at the door, watching the last one disappear up the street.

The moment after she closed the door, someone knocked.
Elma answered.
There were only moths hitting the street-lamp at the corner, and not a soul in sight.
She closed the door and turned.
The shadows of two children, straight and still, stood upon the glowing screen in her darkened living room.

She started.
“Oh! You two about scared the daylights out of me.”

She might have been talking to construction paper cutouts.

“Still full of tricks tonight, are you?” said Elma.

Their forms were stillness personified.

“Okay, one last game.
Do your best and I’ll guess,” she said.
“My guess is you are two bookends — no?” She crept closer.
“The last bowling pins standing — no? Of course not.” She crept closer.
“I know what it is — you are two little rascals!”

Plunging her head behind the curtain Elma was shocked to find no one there.
She stepped back.
The two shadows remained on the white cloth.
The glowing pumpkins around the room seemed to mock, beaming toothy smiles at her.

She stepped back further and found the edge of a chair seat.
“Jessie? Roger? Is that you?”

A measure of delight kept the suddenly cold room at bay.

“It’s not possible, I know — but still.
It’s been thirty-eight years since the war.” She laughed.
“You boys always said your mother put on the best parties around.
You couldn’t resist, could you?”

Nothing.

“I still remember how trim and handsome you two were in uniform, oh.
Just like your Daddy — and proud.
Please don’t just stand there and stare at me.
Be good and let me see your faces once more? My boys, my good boys.” 

Nothing.

Elma broke down and sobbed into her hands.
“There’s no word for it.
That’s how terrible it is.
No mother was meant to outlive her children.”

She stood, angered in tears without comfort.
She grasped the hem and yanked the sheet from its pinnings.

From the street, no one saw the old house windows beam with bright light.
It lasted only a moment.
The pumpkin on the front steps flickered a ‘goodnight,’ and all was stillness.

