= There Came a Knock - Part 2

// previously titled: Jack-O’-Lantern by W.R.Smith (edits and critiques
welcome)

_cont_

Another group arrived and saw a party in the making. The living-room
became a mix of various zombies, a lion tamer, comic book heroes, a
mustachioed villain arm in arm, and cahoots with the likeness of an
unpopular politician. Shining faces and rosy cheeks revealed themselves
as stifling masks were pushed back and worn like hats.

Ventura organized a guessing game while serving up drinks and cookies.
``Guess what in this room I am thinking of,'' she said.

After some hesitation, one answered, ``A candle.''

Another answered, ``A cat!''

``The taste of young human flesh,'' said a wry boy in jeans, a
tee-shirt, and leather jacket. A realistic looking cigarette dangled
from his lip tragically.

``Good answer!'' Ventura pointed at him. ``Only it was wrong, I was
thinking of this bowl of confetti.'' With that, she picked the bowl up
from the table and launched its contents high over the guests. Coming
down, it was soft rains upon Antietam; it was a ticker-tape parade on
Mainstreet of the afterlife. It fell on the astonished young guests and
blessed them one and all. It stuck in their hair and got in their
costumes.

``I like you,'' said a young girl with cat ears and painted-on whiskers.
``Can I take a turn?''

``Sure you may,'' said Ventura, patting the little cat between the ears.

``I spy with my little eye, something cozy and blue.''

They played a couple of mildly entertaining rounds of the game more
before interest fizzled.

Ventura hooked and draped a white tablecloth to make a screen in the
corner of the room. Behind it was a table lamp with its shade removed.
She announced another kind of guessing game. Some of the guests got up,
but she begged them to stay long enough for a few rounds. They glanced
at one another and reluctantly agreed to sit down.

All lights went out except for the flickering Jack O’Lanterns. The
effect was impressive as a hush of excitement became palpable. Ventura
appeared with a flashlight under her chin, lighting her face like from
the days of black and white horror films. Young people laughed with her.

``Now, I want you all to bring your chairs a little closer. This game is
called Shadow-Buff. I know you’ll love it.''

She directed her guests to form groups of two’s and three’s, each
devising a secret they would act out in pantomime behind the screen. The
rule was: the players must perform their roles in silence while the
audience guessed the meaning behind their shadow dance.

It was agreed to begin. As the first contestants stepped forward,
Ventura dipped behind the sheet and turned on the light. She ushered
them behind the impromptu screen, and they let their shadows take over
from there.

The first scenario was an aloof pedestrian, walking in place, and the
shadow of a stalker creeping up from behind. In the end, it was a murder
by knife, horrifically prolonged, even after being called. With boos and
hisses, the audience demanded the next players have their chance.

The art of the medium was quickly absorbed. Ad-lib mimes swung freely
between unbridled madness and moments of baffling brilliance. Distorted
shadows shedding inhibitions, danced and menaced while the audience
shouted for more.

In another scene, a brave lion tamer turned cowardly and got mauled.
Following that, a one-man show illustrated the evolution of walking
posture in five stages, from primate to man. He bent his back one final
time for a sweeping bow.

The Scarecrow and Dorothy borrowed a broom from Ventura. Behind the
screen, the broom hoisted over a shoulder became a rifle. The boy
marched in place. The shadow-girl dabbed a tear from her eye and waved
goodbye with a handkerchief. The play lasted only a moment.

Ventura cried out, ``No, stop. It’s too sad!''

It was immediately apparent the old woman was not joking. Were those not
real tears? All of her guests were astonished. One girl whispered to
another. Together they got up and said it was getting late. More filed
out behind them.

The crowd thinned rapidly. Ventura lingered at the door, watching the
last guest disappear up the street.

The moment after she closed the door, there came a knock. Secretly
pleased, Ventura shook her head in tired dismay as she opened the door.

There were only moths hitting the street-lamp at the corner, and not a
soul in sight. She felt cold, closed the door, and turned. Shadows of
two children, straight and still, stood upon the shadow buff screen in
the dark living room.

She jumped. ``Oh! You two about scared the daylights out of me.''

Their forms were stillness personified.

``Still full of tricks tonight, are you?'' said Ventura. ``Okay, one
last game. My guess is you are two bookends — no?'' She crept closer.
``The last bowling pins standing — no? Of course not.'' She crept
closer. ``I know what it is. You are two little rascals ready for a bowl
of ice cream!''

Plunging her head behind the curtain, Ventura shouted, ``Boo! I got
you.''

No one was there.

She stepped back. The two shadows remained on the white cloth. Around
the room, glowing pumpkins seemed to mock, beaming toothy smiles at her.

She stepped back and bumped into the edge of a chair. She sat down
slowly in awestruck wonder. ``Jessie? Roger? Is that you?''

A measure of delight could not keep her goosebumps at bay.

``It’s not possible, I know — but still. It’s been thirty-eight years
since the war took you away. I’ve missed you so.'' She laughed suddenly.
``But, you boys always said your mama put on the best Halloween party
around. You couldn’t resist, could you?''

She might have been talking to construction paper cutouts. They offered
nothing but to gaze into the dark core of their once familiar shapes.

``I still remember how trim and handsome you two were in uniform, oh.
Just like your Daddy — and proud. Please don’t just stand there and
stare at me. Be good, and let me see your faces once more? My boys, my
good boys.'' There was a pressure mounting inside of somehow knowing it
would be like this. There was only one thing left to do. Ventura broke
down and sobbed into her hands. ``There’s no word for it. That’s how
terrible it is. No mother was meant to outlive her children.''

When she looked up, the two boys were now wearing helmets, their
shoulders squared and thrown back, standing at attention.

Ventura stood up, angered for tears without comfort, souring on life.
Stumbling forward, she grasped the hem of the sheet, yanking it from its
pinnings.

The neighborhood street was empty, as only a matter of timing could
provide. Nobody saw Ventura’s living room window beam with a sudden
bright light. It lasted only a moment and faded, leaving the place
looking dead.

The moths preoccupied with batting at the street lamp had a change of
interest. They flew across the street and up to Ventura’s walk. At the
front doorstep, they accumulated, fluttering in a clamor to get into the
wide grin and pyramid eyes of the giant pumpkin.

With crackles and hissing and wisps of smoke, they doused the stubborn
candlelight with their wings and bodies. So, at last, the Master of
Ceremonies on the front step flickered a `goodnight' to one and all.

END
